name: Clone GitLab Repo

on:
  push:
    branches:
      - main

jobs:
  clone:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository
        uses: actions/checkout@v2

      - name: Generate SSH key
        run: |
          ssh-keygen -t rsa -b 4096 -C "ahmed.benaissa27031999@gmail.com" -f ~/.ssh/id_rsa -N ""
          echo "Generated SSH key: $(cat ~/.ssh/id_rsa.pub)"

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          echo "${{ secrets.GITLAB_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan gitlab.com >> ~/.ssh/known_hosts

      - name: Clone GitLab repository
        run: |
          git clone git@gitlab.com:your-username/your-repo.git
