name: Retrieve Specific GitLab SSH Key

on:
  workflow_dispatch:  # Allows manual trigger
  push:
    branches:
      - test  # Change this to your testing branch

jobs:
  retrieve_key:
    runs-on: ubuntu-latest
    steps:
      - name: Retrieve SSH Keys from GitLab
        id: retrieve_keys
        run: |
          # Get all SSH keys
          keys=$(curl --silent --request GET "https://gitlab.com/api/v4/user/keys" \
          --header "PRIVATE-TOKEN: glft-fWfVx4uCfxUqvkbLQM-y")

          # Filter for the specific key by title
          echo "$keys" | jq '.[] | select(.title == "ci/cd_pipeline")' > filtered_key.json

      - name: Display Retrieved Key
        run: |
          cat filtered_key.json
